### ISSUE TITLE
配色に端末のデフォルト背景色を使えるようにしたい

### ISSUE THREAD

**Issue by arrow2nd** [arrow2nd/nekome#49]
いわゆる透明色の代わりに使いたい

### 実装

```toml
[app]
background_color = ""
```

みたいに色が未指定だったら `tcell.ColorDefault` を使うようにする
